### ISSUE TITLE
Feature desired 

### ISSUE THREAD

**Issue by ghost** [michihiro/aws-console-app#1]
Hello mr Mikihiro
I like his project aws , also because there are very few tools to manage in "a simple way" aws resources .

But I am not be able to use really your console for these cause:
- New EU-Frankfurt zone non implemented 
- No way to start&stop (and other simple common action) on Instances
- Also there is no auto-refresh on instance view, without this the console is not usable also only for monitoring usage,

Please continue your development and , if possible, take care on these suggestion
Best regards

Oscar

**Comment by jmound** [comment]
+1

**Comment by michihiro** [comment]
Thanks for your comment.

**Comment by michihiro** [comment]
389f208c783ad49427850bb12d563f74afbd5215

**Comment by michihiro** [comment]
18bea5107005ccccdf32a94b2e1eb449eba2e99a

**Comment by michihiro** [comment]
4f650c2700172d753dbeff05c37aa2c1b26a776b
